---
apiVersion: v1
kind: Namespace
metadata:
  name: flask-app

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
  namespace: flask-app
  labels:
    app: flask-app
spec:
  replicas: 2  # to run in multiple AZs (if your cluster is multi-AZ)
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: saurabh13/flask-iptime:latest  # change this to your image
          ports:
            - containerPort: 5000
          env:
            - name: TZ
              value: UTC